version: '3.3'  # Optional: Remove this line to silence the obsolete warning

networks:
  robopop:
    driver: bridge
    attachable: true

services:
  epistemics-mysql:
    image: mysql:5.6
    #platform: linux/arm64  # Keep commented if emulation works; uncomment for ARM if switching to mariadb:10.6 later
    networks:
      - robopop
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=selemca
      - MYSQL_PASSWORD=selemca
      - MYSQL_DATABASE=beliefsystem
    volumes:
      - epistemics-data:/var/lib/mysql
    # Removed deploy: mode: global and placement (Swarm-only, ignored anyway)

  epistemics:
    image: robopop/epistemics:1.3.0-snapshot
    #platform: linux/arm64  # Keep commented
    networks:
      - robopop
    ports:
      - target: 8080
        published: 8899
    depends_on:
      - epistemics-mysql
    volumes:
      - epistemics-config:/usr/local/selemca
    # Removed deploy section entirely to default to 1 replica
    # If you need 2 replicas, add back but use dynamic ports or a load balancer (advanced)

  silicon-coppelia:
    image: robopop/silicon-coppelia-gui:latest
    networks:
      - robopop
    ports:
      - target: 8080
        published: 8078
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - ~/.Xauthority:/root/.Xauthority:/ro

volumes:
  epistemics-data:
  epistemics-config: